import Head from 'next/head'
import Link from "next/link"
import Layout from "../../components/Layout"
import { handler } from "../api";

function Sections({ results }) {
  return (
    <Layout>
      <Head>
        <title>Sections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h1>Sections</h1>
          <ul>
            {results?.map(result => <Link href={`sections/${result.section}`}><a>{result.section}</a></Link>)}
          </ul>
        </main>
    </Layout>);
}


// to register for a new New York Times API KEY, visit : 
const API_KEY = "9hUvOqGGdnCBvGKg4EB3L7mGdBC8hKKJ"
// This also gets called at build time
export async function getStaticProps() {

  // Pass post data to the page via props
  return {
    props: {
      results : await handler(`https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`), 
    }
  }
}

export default Sections;
