import Head from 'next/head'
import Layout from "../../components/Layout"
import { handler } from "../api";

function News({ results, title }) {
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h1>{title}</h1>
          <ul>
            {results?.map(result => <li><a href={result.url} rel="noreferrer nofollower">{result.title}</a></li>)}
          </ul>
        </main>
    </Layout>);
}


export async function getStaticPaths() {
  return {
    paths: [
      { params: { path: 'top-stories' } }, 
      { params: { path: 'popular' } }
    ],
    fallback: true // false or 'blocking'
  };
}
const API_KEY = "9hUvOqGGdnCBvGKg4EB3L7mGdBC8hKKJ"
export async function getStaticProps() {
  const URL = `https://api.nytimes.com/svc/topstories/v2/home.json?api-key=${API_KEY}`
  const results = await handler(URL)

  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {
      results, 
      title: "Top Stories" 
    }
  }
}
export default News;
